### PR TITLE
Enable default configuration paths

### LINKED ISSUE #124: Add default config-path to UI
The UI should also be runnable without providing a custom config-path if the config is at a default location.

### PR DESCRIPTION
**Pull request by sjend**
This PR enables loading the configuration from a file named "config.morr" relative to the executeable without specifying a command line argument.
I have added a new profile ("DefaultConfig") which launches the application without any command line arguments for testing purposes.

Closes #124

### CODE REVIEW

**Comment by Gordin508** [comment]
The current setup does not allow specifiying "no-force-german-ui" if no custom configuration path is specified as first parameter. We can keep it like this, but it needs to be documented (e. g. in the usageguide).

**Comment by sjend** [comment]
> 
> 
> The current setup does not allow specifying "no-force-german-ui" if no custom configuration path is specified as first parameter. We can keep it like this, but it needs to be documented (e. g. in the usageguide).

@Gordin508 I have updated the parameter check so it should now work properly with all combinations of configuration and language - if you can, please verify if this indeed fixes the problem.

**Comment by Gordin508** [comment]
> > The current setup does not allow specifying "no-force-german-ui" if no custom configuration path is specified as first parameter. We can keep it like this, but it needs to be documented (e. g. in the usageguide).
> 
> @Gordin508 I have updated the parameter check (the condition wasn't negated) so it should now work properly with all combinations of configuration and language - if you can, please verify if this indeed fixes the problem.

Can confirm all possible combinations of config- and languageargument are accepted and work as expected now.

**Comment by sjend** [comment]
Test failure is unrelated to the latest change and appears to be an issue with the Shared tests - I think it has been fixed already, but I am unsure.

**Pull request merged**
