### PR TITLE
Add tests for clipboard and window management modules

### PR DESCRIPTION
**Pull request by irmasuppes**
- Window Management module tests are ready.

- Clipboard module tests are ready

### CODE REVIEW

**Comment by insightmind** [comment]
Code Coverage in Clipboard Producer seems quite small with about 50% is there a specific reason for that? @irmasuppes

**Comment by limingyialpha** [comment]
I am a bit of curious:
I have found that you have modified all the producers' code to the Unit test purpose:
```
private void WindowHookCallback(GlobalHook.HookMessage msg)
        {
            const int dataParamTest = 1;
            if ((int) msg.wParam == WA_ACTIVE)
            {
                if (msg.Data[0] == dataParamTest)
                {
                    var @event = new WindowFocusEvent
                    {
                        IssuingModule = WindowManagementModule.Identifier,
                        ProcessName = "sampleProcessName",
                        Title = "sampleFocusTitle"
                    };
                    Enqueue(@event);
                    return;
                }

                var hwnd = nativeWindowManagement.GetForegroundWindow();
                if (lastHwnd != hwnd)
                {
                    var processName = nativeWindowManagement.GetProcessNameFromHwnd(hwnd);
                    var windowTitle = nativeWindowManagement.GetWindowTitleFromHwnd(hwnd);
                    var @event = new WindowFocusEvent
                    {
                        IssuingModule = WindowManagementModule.Identifier,
                        ProcessName = processName,
                        Title = windowTitle
                    };
                    Enqueue(@event);
                }

                lastHwnd = hwnd;
            }
        }
```
To my understanding, if user designed a fake message and set the `msg.Data[0] =dataParamTest`,
The producer's callback will return a fixed Event for the test purpose.
But is it a good practice to modify the source code of the producers for the purpose of Unit tests?
(Because then the part of the code you added for the test become a part of the source code and there also should be a test for it.)
Shouldn't we mock the `INativeWindowsManagement` and use the SetUp method instead?

**Comment by insightmind** [comment]
Yes this does not seem good practice. You should only consider changing the main code in for example if you need to inject a custom API code or if you have extensive usage of singletons. Which is not present in our code.

It would be nice if you could change that, so the actual implementation is being tested. As this is only about two properties of the event you should be able to do this without a problem. As long as you mock the GlobalHook or IHookNativeMethods you should be able to achieve this quite easily. I think it is pretty similar to the tests in MouseModule.

**Comment by insightmind** [comment]
You can mock the NativeWindow the same way as we mocked the IHookNativeMethods

**Pull request merged**
